### ISSUE TITLE
Unable to do any edits at all

### ISSUE THREAD

**Issue by Alinya** [timcrockford/track-custom-keywords#1]
I'm unable to edit the URL from the admin panel at all after installing this plugin. Below are possible conflicting plugins that I am using as well:

Separate Users
Don't Track Admins
Change Password
Authorization Manager
Random Keywords
Upload and Shorten

All plugins used are available from: https://github.com/YOURLS/YOURLS/wiki/Plugin-List
Version of your plugin used: 0.1

**Comment by timcrockford** [comment]
Hi Alinya! When you say you're unable to edit URLs, are you getting an "Access Denied" error or is something else going wrong?

I've just tried installing the same combination of plugins and if that's the error you're seeing it's to do with a conflict with Authorisation Manager. Will see if I can work out a way for my plugin to play nice with that one, however if you could please provide some more detail on what you're seeing so I can track down other issues that would be appreciated!

**Comment by timcrockford** [comment]
Okay, the reason the "Access Denied" error is coming up is because I've defined a new edit function hook called "edit_save_custom" so as not to interfere with the existing function. The original "edit_save" function is hardcoded into the AuthMgr plugin code, and because my function has a new name, it's failing.

Let's see if I can hook into the AuthMgr capability map to add my function to it.

**Comment by timcrockford** [comment]
Alright, first the technical explanation. The authmgr_intercept_admin function in the AuthMgr plugin is completely self contained, and only checks a set link of functions, and denies the others by default. This means my edit_save_custom function is blocked by AuthMgr. I've had a quick play with some options but I don't think it's something that can be fixed on my side without AuthMgr providing some additional hooks for other plugins to hook into it.

Short explanation - the two plugins are currently incompatible with each other due to the way AuthMgr operates.

If you want to make this work on your own installation, you can add a line into the AuthMgr plugin.php file to make it work. Look for this line:

'edit_save' => AuthmgrCapability::EditURL,

Add another line beneath it that looks like this (don't delete the existing line though).

'edit_save_custom' => AuthmgrCapability::EditURL,

That will allow AuthMgr to look for the custom function my plugin is using, and apply the same rules around edits that it does to the usual edit link function.

Not an ideal answer I realise, but it will let both coexist in the same installation.

**Comment by Alinya** [comment]
The solution is ideal enough for me, thanks! I don't mind editing it to add in that line, and finally, it works! Thanks once again :+1:  :)
Edit: I made a fork of his program with your recommended edit: https://github.com/Alinya/yourls-authmgr-plugin :)

**Comment by joshp23** [comment]
please see https://github.com/nicwaller/yourls-authmgr-plugin/issues/15
